name: Test Workflow 1
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World!"
      - name: Goodbye message
        run: echo "Goodbye! Ending workflow"
